### ISSUE TITLE
cmd/scriggo: support transformation of package-less programs into programs

### ISSUE THREAD

**Issue by zapateo** [open2b/scriggo#251]
Implement a tool that, given:

- a _Scriggofile_
- a Scriggo script

generates a program source code that is 100% compatible with Go.

The Scriggofile must have a limitation: packages imported using `main` cannot have `uncapitalize` or selective importing. This allow to transform

```
IMPORT mypkg AS MAIN
```

into

```go
import . "mypkg"
```

The script source code must be transformed in the following ways:

- it's content must be encapsulated into a main function into a main package
- functions defined using the script syntax must be converted to function literals assigned to variables
- if the last statement of the script is an expression statement not valid in Go, such expression must be assigned to the blank identifier

**Comment by gazerro** [comment]
Support for scripts has been removed in the commit f423f045394dc5364d9de0ec94413cc26af34a6c. Close this issue.
