### ISSUE TITLE
compiler/parser: false positive 'method declarations are not supported' in scripts

### ISSUE THREAD

**Issue by zapateo** [open2b/scriggo#667]
This package less program:

```go
func() {
    Print("hello")
}()
```

returns an error in Scriggo:

```
syntax error: method declarations are not supported in this release of Scriggo
```

but actually there is not method declaration.

**Comment by gazerro** [comment]
Support for scripts has been removed in the commit f423f045394dc5364d9de0ec94413cc26af34a6c. Close this issue.
