### ISSUE TITLE
proposal: benchmarks: add gomacro to benchmarks

### ISSUE THREAD

**Issue by gazerro** [open2b/scriggo#870]
[gomacro](https://github.com/cosmos72/gomacro) is a pure Go interpreter, so it should be added to the benchmarks.

**Comment by gazerro** [comment]
gomacro uses `unsafe` to execute code. I think we shouldn't add to the benchmarks, interpreters that use the `unsafe` packages, or use cgo or assembly code.

**Comment by maisola-work** [comment]
> gomacro uses `unsafe` to execute code. I think we shouldn't add to the benchmarks, interpreters that use the `unsafe` packages, or use cgo or assembly code.

I agree, we should check that the interpreters we already added to the benchmarks respect this criteria, and add a note to the README and the scriggo site benchmarks page explaining the ratio of our choice.
