### ISSUE TITLE
docs: show how to pass variables to template in template.Run

### ISSUE THREAD

**Issue by kjk** [open2b/scriggo#871]
I just found out about scriggo and it looks very promising.

From the perspective of someone new to to the project: I was trying to figure out how to execute a simple template.

Not a single example in readme.md or scriggo.com seems to show how to pass values (variables) from code to a template.

I kind of guessed that one of the `template.Run` arguments is for that, but this should be explicitly stated.

Suggestion: modify the template execution example https://github.com/open2b/scriggo/#execute-a-scriggo-template-in-your-application to one that shows passing variables to a template. The simplest change: make `who` variable be passed from the code.

The same applies to https://scriggo.com/get-started-2

**Comment by kjk** [comment]
Actually, I can't figure out how to pass a variable to a template. 

I thought it's going to be like Go templates when I provide variables for template execution but it seems that if I'm using a variable, I have to pre-declare it as a global for `scriggo.BuildTemplate` but the only examples for globals are functions.

I want to do something like:
```
{% for e in toc %}
  {{ e.Name }}
{% end %}
```
Where `toc` is `[]*tocNode` where `tocNode` is a struct with `Name` field.

I tried:
```go
func genTocHTML(toc []*tocNode) string {
	fsys := scriggo.Files{
		"toc.tmpl.html": []byte(tocTmpl),
	}
	globals := native.Declarations{
		"toc": toc,
	}
	opts := scriggo.BuildOptions{
		Globals: globals,
	}
	template, err := scriggo.BuildTemplate(fsys, "toc.tmpl.html", &opts)
```

but I get: `importing package main, declaration "toc" is not valid`

Is this even supported?

If yes, how do I build `nativeDeclarations{}` ?

Is `vars` argument to `template.Run()` the same as `BuildOptions{Globals:}` ?
(they have different type)

**Comment by gazerro** [comment]
@kjk Thank you for posting this issue.

To pass a variable to a template, pass a pointer to the variable:

```go
 globals := native.Declarations{
        "toc": &toc,
}
```

and in the template access to the variable without deferencing it. This works:

```
{% for e in toc %}
  {{ e.Name }}
{% end %}
```

Note that in this case the variable is "shared" between your code and the template code, so if you assign a new value to `toc` in the template, the `toc` variable in your Go code will also have that value.

Scriggo also supports other use cases when passing a variable to template. For example, you can pass a `nil` pointer:

```go
 globals := native.Declarations{
        "toc": []*tocNode(nil),
}
```

and then pass the value of the variable to the `Run` method:

```go
err = template.Run(out, map[string]interface{}{ "toc" : toc }, nil)
```

In this case, if the variable `top` is assigned in the template, the `toc` variable in the Go code does not change.

**Comment by gazerro** [comment]
@kjk

> Suggestion: modify the template execution example https://github.com/open2b/scriggo/#execute-a-scriggo-template-in-your-application to one that shows passing variables to a template. The simplest change: make `who` variable be passed from the code.

We have changed the template example as you suggested. Thanks.

**Comment by gazerro** [comment]
The commit open2b/scriggo-site@617c068e8073797fde352e12c63f63f0bda1e29d has added the missing documentation on the site. So I close this issue.
