### ISSUE TITLE
//go:notinheap and type checking errors

### ISSUE THREAD

**Issue by zapateo** [open2b/scriggo#895]
Consider this code:

```go
package main

type a struct{}

//go:notinheap
type b a

var _ = (*b)(new(a))

func main() {
	println("hey")
}
```

Scriggo compiles and runs, printing:

```
hey
```

gc, instead, returns a type checking error:

```
8:13: cannot convert new(a) (type *a) to type *b:
        b is incomplete (or unallocatable), but a is not
```

How should we handle this?

**Comment by zapateo** [comment]
@gazerro what do you think?

**Comment by gazerro** [comment]
The `notinheap` directive is specific of the gc compiler, so Scriggo behaves correctly for me.

**Comment by zapateo** [comment]
> The `notinheap` directive is specific of the gc compiler, so Scriggo behaves correctly for me.

I agree. Closing this issue.
