### ISSUE TITLE
proposal: compiler: add 'else' block in for range statement

### ISSUE THREAD

**Issue by knz** [open2b/scriggo#934]
In the Go `template` package, it's possible to use a `else` block when the iteration traverses no elements, like this:

```
{{range X}}
  do something repeatedly...
{{else}}
  do something if X was empty
{{end}}
```

Currently it's very cumbersome to do something equivalent with Scribbo. It would be nice if `for` could support an `else` block like Go's `template`.

**Comment by gazerro** [comment]
Currently you can write

```
{% for product in products %}

{% end for %}
{% if not products %}

{% end if %}
```

I agree that it is cumbersome. Therefore the proposal is to add an `else` statement to the `for range` statements and the `else` block is executed if the range expression is empty. For example

```
{% for product in products %}

{% else %}

{% end for %}
```

```
{% for i, product := range products %}

{% else %}

{% end for %}
```

**Comment by knz** [comment]
It's not just cumbersome - if the source of the range has side effects (or is a channel), it's not possible to write `{{ if not ... }}` after the source has been consumed already. Instead the pattern becomes:

```
{% hasItems := false %}
{% for product in products %}
  {% hasItems = true %}
  ...
{% end for %}
{% if not hasItems %}

{% end if %}
```

and that is much less readable and more prone to errors.
