### ISSUE TITLE
proposal: allow accessing map keys like fields in templates

### ISSUE THREAD

**Issue by ernado** [open2b/scriggo#937]
Also, allow implicit cast from `interface{}` to `map[string]interface{}` or `map[string]T` on indexing.

So, I want following to be possible:
```go
{{ data.foo.bar.key }}
```

Instead of:
```go
{{ data["foo"].(map[string]interface{})["bar"].(map[string]interface{})["key"] }}
```

Full test example:
```go
package maps_test

import (
	"bytes"
	"testing"

	"github.com/open2b/scriggo"
	"github.com/open2b/scriggo/native"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestMap(t *testing.T) {
	var data map[string]interface{}
	require.NoError(t, yaml.Unmarshal([]byte(`---
foo:
  bar:
    key: "value"
    number: 1
`), &data))
	for _, tt := range []struct {
		Name  string
		Value string
	}{
		{
			Name:  "Explicit",
			Value: `{{ data["foo"].(map[string]interface{})["bar"].(map[string]interface{})["key"] }}`,
		},
		{
			Name:  "Implicit",
			Value: `{{ data.foo.bar.key }}`,
		},
	} {
		t.Run(tt.Name, func(t *testing.T) {
			fsys := scriggo.Files{"index.html": []byte(tt.Value)}
			opts := &scriggo.BuildOptions{
				Globals: native.Declarations{"data": &data},
			}
			template, err := scriggo.BuildTemplate(fsys, "index.html", opts)
			require.NoError(t, err)

			b := new(bytes.Buffer)
			require.NoError(t, template.Run(b, nil, nil))
		})
	}
}
```
```
index.html:1:8: data.foo undefined (type map[string]interface {} has no field or method foo)
```

**Comment by gazerro** [comment]
Certainly it would be nice to be able to type `data.foo.bar.key` to access maps but I think this leads to a lot of specification and implementation complications.

It would make `map[string]T` a special case with respect to other map types and its keys which are representable as identifiers in Go would be special cases with respect to all possible string keys.

Also, if `data` implements a method called `Foo`, then `data.Foo` would be ambiguous.

This solution would in practice only be used with `{{ ... }}` because if you write

```
{% s := data.foo.bar.key %}
```

The type of `s` will be `interface{}` and not `string`, if `data.foo.bar` has type `map[string]interface{}`.

**Comment by gazerro** [comment]
An alternative, which can be used right now, is to define a built-in function or type. For example

```
{{ data.Get("foo.bar.key") }}
```

In this case you can also define specific behaviors such as

```
{{ data.MustGet("foo.bar.key") }}
```

**Comment by ernado** [comment]
Agree that it is non-trivial, will require a lot of specification and decisions on trade-offs.

However, I'm pretty sure that it is important feature.
My use case is to allow end-users to allow providing arbitrary values to template, what is possible in jinja or is used in helm charts.

For example: https://helm.sh/docs/chart_template_guide/values_files/

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink }}
  food: {{ .Values.favorite.food }}
```

The `.Values` is `map[string]any`.

So, providing the full test where the difference between `text/template` and scriggo is shown:
```go
package maps_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/open2b/scriggo"
	"github.com/open2b/scriggo/native"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestMap(t *testing.T) {
	var values map[string]any
	require.NoError(t, yaml.Unmarshal([]byte(`---
foo:
  bar:
    key: "value"
    number: 1
`), &values))
	t.Run("Standard", func(t *testing.T) {
		b := new(bytes.Buffer)
		tpl := template.Must(template.New("").
			Parse(`{{ .Values.foo.bar.key }}`),
		)
		require.NoError(t, tpl.Execute(b, struct {
			Values map[string]any
		}{
			Values: values,
		}))
		t.Log(b)
	})
	t.Run("Scriggo", func(t *testing.T) {
		for _, tt := range []struct {
			Name  string
			Value string
		}{
			{
				Name:  "Explicit",
				Value: `{{ Values["foo"].(map[string]interface{})["bar"].(map[string]interface{})["key"] }}`,
			},
			{
				Name:  "Implicit",
				Value: `{{ Values.foo.bar.key }}`,
			},
		} {
			t.Run(tt.Name, func(t *testing.T) {
				fsys := scriggo.Files{"index.html": []byte(tt.Value)}
				opts := &scriggo.BuildOptions{
					Globals: native.Declarations{"Values": &values},
				}
				tpl, err := scriggo.BuildTemplate(fsys, "index.html", opts)
				require.NoError(t, err)

				b := new(bytes.Buffer)
				require.NoError(t, tpl.Run(b, nil, nil))
			})
		}
	})
}
```

**Comment by newbeelearn** [comment]
+1 It would be great if this proposal is accepted. It would make the transition from jinja, text/templates smooth.

**Comment by gazerro** [comment]
## Proposal to extend the selector expression to maps

If `m` has type `map[string]T` and `x` is an identifier, `m.x` is a selector expression, with type `T`, that denotes the key `"x"` of `m`. `x` is called `key selector`.  Writing `m.x` is the same as writing `m["x"]`.

As a special case, if `T` is `interface{}`, that is, `m` has type `map[string]interface{}`, there can be more than one key selector as in

```
m.x.y.z
```

and writing `m.x.y.z` is the same as writing `m["x"].(map[string]interface{})["y"].(map[string]interface{})["z"]`.

For example, given the declarations: 

```
var t map[string]string
var s map[string]interface{}
var p map[string]map[string]int
```

one may write: 

```
t.x        // t["x"] with type string
s.y        // s["y"] with type interface{}
s.y.z      // s["y"].(map[string]interface{})["z"] with type interface{}
p.x        // p["x"] with type map[string]int
p.x.y      // p["x"]["y"] with type int
```
